In [1]:
#importing numpy
import numpy as np

In [2]:
# Defining 1D array
array1D = np.array([1, 2, 3, 4])
array1D

array([1, 2, 3, 4])

In [3]:
# Defining 2D array
array2D = np.array([
    [1, 2, 3, 4],
    [4, 5, 6, 7],
    [3, 6, 8, 0]
])
array2D

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [3, 6, 8, 0]])

In [5]:
# Defining 3D array
array3D = np.array([
    [
        [1, 2, 3, 4],
        [4, 3, 2, 1]
    ],
    [
        [0, 9, 8, 7],
        [6, 7, 8, 9]
    ]
])
array3D

array([[[1, 2, 3, 4],
        [4, 3, 2, 1]],

       [[0, 9, 8, 7],
        [6, 7, 8, 9]]])

In [6]:
# memory address
array2D.data

In [7]:
# shape
array3D.shape

(2, 2, 4)

In [8]:
# dimension
array3D.ndim

3

In [9]:
# datatype
array3D.dtype

dtype('int32')

In [11]:
# array of ones
ones = np.ones((3, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# array of zeros
zeros = np.zeros((2, 3, 4), dtype=np.int16)
zeros

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [14]:
zeros.shape

(2, 3, 4)

In [15]:
# array with random variables
np.random.random((2,2))

array([[0.57368981, 0.01008603],
       [0.14132107, 0.62891473]])

In [17]:
# empty array
empty = np.empty((3, 2))
empty

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
# full array
full = np.full((2, 2), 7)
full

array([[7, 7],
       [7, 7]])

In [21]:
# array of evenly spaced values
evenlySpaced1 = np.arange(10, 25, 5)
evenlySpaced1

array([10, 15, 20])

In [22]:
evenlySpaced2 = np.linspace(10, 25, 5)
evenlySpaced2

array([10.  , 13.75, 17.5 , 21.25, 25.  ])